#pragma once
#define WM_UIUPDATE WM_USER+1
#define WM_DISPLAYUIUPDATE WM_USER+2
#define WM_GRAPHUPDATE WM_USER+3
#define WM_PM_CHANGE WM_USER+4
#define WM_DISPLAYCOMBOBOXUPDATE WM_USER+5
#define WM_TIME_UNIT WM_USER+6
#define WM_REVIEW_UPDATE WM_USER+7
#define WM_RECORD_START WM_USER+7
#define WM_RECORD_FINISH WM_USER+8
#define WM_REVIEW_COMBO_UPDATE WM_USER+9
#define WM_UPDATE_BTN_HOLD WM_USER+10
#define WM_UNITUPDATE WM_USER+11
#define WM_INITIALIZE WM_USER+12
#define WM_DLG_INITIALIZE WM_USER+13
#define WM_WORK_UPDATE WM_USER+14