//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// AGMDMonitor.rc에서 사용되고 있습니다.
//
#define IDCANCEL2                       3
#define IDOK2                           4
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_AGMDMonitorTYPE             130
#define IDD_MONITORDLG                  310
#define IDD_OPPANELDLG                  311
#define IDD_VIEWDLG                     312
#define IDD_SENSORVIEWDLG               313
#define IDD_SENSORSTATUSDLG             314
#define IDD_BROWSERDLG                  315
#define IDD_COMSET                      316
#define IDD_SETGAPCRITERIADLG           317
#define IDD_STATIONINFOMATION           318
#define IDD_ENVSETTINGDLG               319
#define IDD_CAL1                        320
#define IDD_CAL2                        321
#define IDD_REPORT                      322
#define IDD_CALIBRATION                 328
#define IDB_SESOMARK                    331
#define IDC_RADIO1                      1000
#define IDC_RADIO_NONE                  1000
#define IDC_RADIO2                      1001
#define IDC_RADIO_OFFSET                1001
#define IDC_BUTTON1                     1002
#define IDC_BTN_PREV                    1002
#define IDC_BTNLOAD                     1002
#define IDC_CHECK1                      1003
#define IDC_BUTTON2                     1003
#define IDC_CHK_AUTO_CMD                1003
#define IDC_BTN_DATAAPPLY               1003
#define IDC_COMBO1                      1004
#define IDC_CB_BROWSER                  1004
#define IDC_COMBO2                      1005
#define IDC_CB_GINT                     1005
#define IDC_STATIC_GAP1                 1006
#define IDC_STATIC_GAP2                 1007
#define IDC_STATIC_GAP3                 1008
#define IDC_EDIT1                       1008
#define IDC_EDT_JIGGAP                  1008
#define IDC_EDIT2                       1009
#define IDC_EDIT_STATION                1009
#define IDC_EDT_DFNAME                  1009
#define IDC_EDIT3                       1010
#define IDC_EDIT_TOOL                   1010
#define IDC_EDIT_GAP1_TOLERANCE         1011
#define IDC_EDIT4                       1011
#define IDC_EDIT_COMMENT                1011
#define IDC_PROGRESS1                   1012
#define IDC_PROGRESS_BATTERY            1012
#define IDC_EDIT_GAP2_TARGET            1012
#define IDC_EDIT6                       1013
#define IDC_RADIO_VIEW                  1013
#define IDC_EDIT_GAP2_TOLERANCE         1013
#define IDC_EDIT7                       1014
#define IDC_RADIO_REVIEW                1014
#define IDC_EDIT_GAP3_TARGET            1014
#define IDC_EDIT8                       1015
#define IDC_STAT_CONNECT                1015
#define IDC_EDIT_DISPLAY_NUM            1015
#define IDC_STATIC_TEMPERATURE          1016
#define IDC_BATTNUM                     1017
#define IDC_LGAP1                       1018
#define IDC_LGAP2                       1019
#define IDC_LGAP3                       1020
#define IDC_RADIO_INCHES                1021
#define IDC_RADIO_MM                    1022
#define IDC_EDIT_ALL_TARGET             1023
#define IDC_EDIT_GAP1_TARGET            1024
#define IDC_EDIT_ALL_TOLERANCE          1025
#define IDC_EDIT_GAP3_TOLERANCE         1026
#define IDC_STATIC_ALL_TARGET_UNIT      1027
#define IDC_STATIC_GAP1_TARGET_UNIT     1028
#define IDC_STATIC_GAP2_TARGET_UNIT     1029
#define IDC_STATIC_GAP3_TARGET_UNIT     1030
#define IDC_STATIC_ALL_TOLERANCE_UNIT   1031
#define IDC_STATIC_GAP1_TOLERANCE_UNIT  1032
#define IDC_STATIC_GAP2_TOLERANCE_UNIT  1033
#define IDC_STATIC_GAP3_TOLERANCE_UNIT  1034
#define IDC_STATIC_ALL                  1035
#define IDC_CHECK_ALL_GAP_SAME          1036
#define IDC_EDIT_VIEW_RANGE             1037
#define IDC_CBPORTNO                    1038
#define IDC_CBBAUDRATE                  1039
#define IDC_STATIC_GAP1_UNIT            1041
#define IDC_STATIC_GAP2_UNIT            1042
#define IDC_STATIC_GAP3_UNIT            1043
#define IDC_STATIC_GAP1_TOL             1045
#define IDC_STATIC_GAP2_TOL             1046
#define IDC_STATIC_GAP3_TOL             1047
#define IDC_BTN_APPLY                   1048
#define IDC_EDIT_OFFSET_GAP1            1049
#define IDC_EDIT_OFFSET_GAP2            1050
#define IDC_EDIT_OFFSET_GAP3            1051
#define IDC_STATIC_1                    1052
#define IDC_STATIC_2                    1053
#define IDC_STATIC_3                    1054
#define IDC_BTN_READ                    1055
#define IDC_BTN_NEXT                    1055
#define IDC_LST_CALIBRATIONRESULT       1056
#define IDC_EDIT_OPERATOR               1057
#define IDC_BTN_CLEAR                   1058
#define IDC_EDT_SAVEFOLDER              1059
#define IDC_BTN_SETFOLDER               1060
#define IDC_CB_INTNO                    1061
#define IDC_STATIC_TOTAL_DISPLAY_NUM    1062
#define IDC_NREPORTDATA                 1063
#define IDC_CALINFO                     1064
#define ID_SETTINGS_SETGAPCRITERIA      32771
#define ID_SETTINGS_SETSTATIONINFORMATION 32772
#define ID_SETTINGS_SETGAPOFFSETS       32773
#define ID_SETTINGS_SETDISPLAYORIENTATION 32774
#define ID_SETTINGS_COMPORTSETTING      32774
#define ID_SETDISPLAYORIENTATION_NOTCHAT2O 32775
#define ID_SELECTCOLORS_TOLERANCE       32775
#define ID_SETDISPLAYORIENTATION_NOTCHAT2O32776 32776
#define ID_SETTINGS_CALIBRATION         32776
#define ID_SETDISPLAYORIENTATION_NOTCHAT6O 32777
#define ID_SETTINGS_ENVIRONMENTSETTING  32777
#define ID_SETDISPLAYORIENTATION_NOTCHAT8O 32778
#define ID_ENVSET                       32778
#define ID_SETDISPLAYORIENTATION_NOTCHAT10O 32779
#define ID_ENV_SET                      32779
#define ID_SETDISPLAYORIENTATION_NOTCHAT12O 32780
#define ID_FILE_SAVE32780               32780
#define ID_SET_NOTCH_2                  32781
#define ID_LOG_SAVE                     32781
#define ID_SET_NOTCH_4                  32782
#define ID_EXPORT_CSV                   32782
#define ID_SET_NOTCH_6                  32783
#define ID_SET_NOTCH_8                  32784
#define ID_FILE_EXPORT_EXCEL            32784
#define ID_SET_NOTCH_10                 32785
#define ID_EXPORT_EXCEL                 32785
#define ID_SET_NOTCH_12                 32786
#define ID_SETTINGS_SELECTCLOROS        32787
#define ID_EXCEL                        32787
#define ID_SELECTCOLORS_SPECIN          32788
#define ID_SELECTCOLORS_SPECOUT         32789
#define ID_FILE_EXIT                    32789
#define ID_SELECTCOLORS_SPECT           32790
#define ID_SELECTCOLORS_GAPDISPLAY      32790
#define ID_SPECOUT_GAPISTOOSMALL        32791
#define ID_SPECOUT_GAPISTOOBIG          32792
#define ID_SAVE_AS_LOG                  32792
#define ID_FILE_SAVEASLOGFILE           32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32796
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           323
#endif
#endif
