//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// AVMDMonitor.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_AVMDMonitorTYPE             130
#define IDD_DISPLAY                     310
#define IDD_TIME                        319
#define IDD_GRAPH                       320
#define IDD_FFT_GRAPH                   321
#define IDD_COMSET                      322
#define IDD_SCROLLDLG                   323
#define IDD_SCROLL                      323
#define IDD_VIEW                        328
#define IDD_REVIEW                      329
#define IDD_SET_GO_NOGO                 333
#define IDD_SET_EVENT_SETTING           333
#define IDD_STATION_INFORMATION         334
#define IDD_SET_FILTER                  336
#define IDD_SET_TIME_DOMAIN_FORMAT      338
#define IDD_ANNOTATE_MARK               339
#define IDD_ENVSETTING                  341
#define IDD_TEMPDLG                     342
#define IDD_MARKEDIT                    343
#define IDD_PROGRESSBARDLG              345
#define IDB_SESOMARK                    346
#define IDD_PARTIALSAVE                 348
#define IDI_ICON1                       350
#define IDI_ICON2                       356
#define IDI_ICON_BACKPLAY               361
#define IDI_ICON_PLAY                   362
#define IDI_ICON_FAST_BACKPLAY          363
#define IDI_ICON_FAST_PLAY              364
#define IDI_ICON_STOP                   365
#define IDI_ICON_PAUSE                  365
#define IDR_TESTMENU                    366
#define IDC_BTN_SETFOLDER               1000
#define IDC_BTN_ITEMUP                  1000
#define IDC_BTN_ClearNoGo               1001
#define IDC_CHK_TRACK_RMS               1002
#define IDC_CHK_TRACK_X                 1003
#define IDC_CHK_TRACK_Y                 1004
#define IDC_CHK_TRACK_Z                 1005
#define IDC_STATIC_DISPLAY              1006
#define IDC_CB_TIME_SCALE               1010
#define IDC_CB_HOFRZON_SCALE            1011
#define IDC_CHK_FFT_SHOW                1012
#define IDC_EDT_SAVEFOLDER              1012
#define IDC_CB_FS_SCALE                 1013
#define IDC_EDT_DFNAME                  1013
#define IDC_CHK_SHOW_LINE               1014
#define IDC_STATIC_FILTER_STATUS        1015
#define IDC_STATIC_TIME                 1016
#define IDC_STATIC_SAMPLE_SIZE          1017
#define IDC_CB_RECORD_TIME              1018
#define IDC_CB_RECORD_DEGREE            1019
#define IDC_BTN_START                   1020
#define IDC_BTN_FINISH                  1021
#define IDC_EDT_MARKNAME                1025
#define IDC_LSTB_MARK                   1026
#define IDC_BTN_ITEMPDOWN               1027
#define IDC_BTN_ITEMDEL                 1028
#define IDC_PROGRESS_CONNECT            1029
#define IDC_BTN_ITEMINS                 1029
#define IDC_PROGRESS_BATTERY            1030
#define IDC_BTN_ITEMUPDATE              1030
#define IDC_PROGRESS_TEMPERATURE        1031
#define IDC_STATIC_CONNECT              1032
#define IDC_BTN_ITEMLOAD                1032
#define IDC_STATIC_BATTERY              1033
#define IDC_STATIC_TEMPERATURE          1034
#define IDC_BTN_ITEMSAVE                1034
#define IDC_BTN_ADD                     1035
#define IDC_CBPORTNO                    1038
#define IDC_CBBAUDRATE                  1039
#define IDC_BUTTON1                     1039
#define IDC_BTN_COMPARE                 1039
#define IDC_BTN_NEXT                    1039
#define IDC_BTN_RECORD_FINISH           1040
#define IDC_BTN_ADD_MARK                1041
#define IDC_SCROLLBAR4                  1044
#define IDC_SCROLLBAR                   1044
#define IDC_STATIC_MODE                 1051
#define IDC_RADIO_VIEW                  1052
#define IDC_RADIO_REVIEW                1053
#define IDC_STATIC_RECORDDATA           1054
#define IDC_CB_RECORDTIME               1055
#define IDC_CB_RECORDUNIT               1056
#define IDC_BTN_RECORD_START            1057
#define IDC_STATIC_RECORD_STATUS        1058
#define IDC_BTN_RECORD_NOMALBACK        1058
#define IDC_BTN_HOLD                    1058
#define IDC_BTN_RECORD_NOMALSTART       1059
#define IDC_BTN_RECORD_FASTSTART        1060
#define IDC_COMBO1                      1063
#define IDC_CB_TIME                     1063
#define IDC_CB_QUALIFICATION            1063
#define IDC_CB_SPEED                    1063
#define IDC_COMBO2                      1064
#define IDC_CB_UNIT                     1064
#define IDC_SLIDER1                     1065
#define IDC_SLIDER_REVIEW               1065
#define IDC_CB_DATARANGE                1065
#define IDC_BUTTON2                     1066
#define IDC_BTN_APPLY                   1066
#define IDC_BTN_REVIEW_GO               1066
#define IDC_CB_VIEWRANGE                1066
#define IDC_BUTTON3                     1067
#define IDC_BTN_COMPARE_GO              1067
#define IDC_EDIT_                       1068
#define IDC_EDIT_DATA                   1068
#define IDC_BTN_RECORD_FASTBACK         1069
#define IDC_BTN_MOVEPOS                 1070
#define IDC_COMBO3                      1071
#define IDC_BUTTON5                     1072
#define IDC_BUTTON6                     1073
#define IDC_BTN_MARK_PREV               1073
#define IDC_BUTTON7                     1074
#define IDC_BTN_MARK_NEXT               1074
#define IDC_BUTTON8                     1075
#define IDC_BTN_ADDMARK                 1075
#define IDC_BTN_COMPARE_MARK_PREV       1075
#define IDC_BUTTON9                     1076
#define IDC_BTN_MARK_UPDATE             1076
#define IDC_BUTTON10                    1077
#define IDC_BTN_MARK_DELETE             1077
#define IDC_CHECK1                      1078
#define IDC_BUTTON15                    1078
#define IDC_BTN_COMPARE_MARK_NEXT       1078
#define IDC_CHECK2                      1079
#define IDC_BTN_MARK_PREV2              1079
#define IDC_COMBO4                      1080
#define IDC_COMBO5                      1081
#define IDC_BUTTON16                    1081
#define IDC_BTN_COMPARE_MARK_UPDATE     1081
#define IDC_BUTTON11                    1082
#define IDC_CHECK8                      1082
#define IDC_CHK_Y_BELOW                 1082
#define IDC_BTN_Compare_MarkDelete      1082
#define IDC_BTN_COMPARE_MARK_DELETE     1082
#define IDC_BUTTON12                    1083
#define IDC_BUTTON13                    1084
#define IDC_SLIDER2                     1085
#define IDC_SLIDER_COMPARE              1085
#define IDC_SLIDER_FFT_SHOW             1085
#define IDC_BUTTON4                     1086
#define IDC_EDIT1                       1086
#define IDC_BTN_MARK_PREV3              1086
#define IDC_BTN_BACK_PLAY               1086
#define IDC_BUTTON14                    1087
#define IDC_EDIT2                       1087
#define IDC_RADIO1                      1087
#define IDC_EDT_TOOL                    1087
#define IDC_BTN_MARK_PREV4              1087
#define IDC_BTN_PLAY                    1087
#define IDC_EDIT_2                      1088
#define IDC_EDIT3                       1088
#define IDC_RADIO2                      1088
#define IDC_EDT_STATION                 1088
#define IDC_BTN_MARK_PREV5              1088
#define IDC_BTN_FAST_BACKPLAY           1088
#define IDC_BTN_MOVEPOS2                1089
#define IDC_EDIT4                       1089
#define IDC_CB_SAMPLESIZE               1089
#define IDC_EDT_COMMENT                 1089
#define IDC_BTN_FAST_PLAY               1089
#define IDC_COMBO6                      1090
#define IDC_CB_FILTERNAME               1090
#define IDC_EDIT_LOW_VALUE              1091
#define IDC_EDIT8                       1092
#define IDC_EDIT_HIGH_VALUE             1092
#define IDC_EDIT_Z_ABOVE                1092
#define IDC_CHK_ENABLE_FILTER           1093
#define IDC_COMBO_TIME                  1094
#define IDC_PRGCNT                      1096
#define IDC_EDIT9                       1097
#define IDC_BATTNUM                     1097
#define IDC_EDIT_NOGO_VALUE             1097
#define IDC_CHK_RMS                     1098
#define IDC_CHK_X_ABOVE                 1099
#define IDC_CHK_X_BELOW                 1100
#define IDC_CHK_Y_ABOVE                 1101
#define IDC_CHK_Z_ABOVE                 1102
#define IDC_CHK_Z_BELOW                 1103
#define IDC_EDIT_RMS_ABOVE              1104
#define IDC_EDIT_X_ABOVE                1105
#define IDC_EDIT_X_BELOW                1106
#define IDC_EDIT_Y_ABOVE                1107
#define IDC_EDIT_Y_BELOW                1108
#define IDC_EDIT_Z_BELOW                1109
#define IDC_RADIO_TRIGGER               1110
#define IDC_STATIC_EVENT_TYPE           1111
#define IDC_RADIO_NONE                  1112
#define IDC_RADIO_GONOGO                1113
#define IDC_CB_FFT_HOFRZON_SCALE        1115
#define IDC_STATIC_TOTAL_COUNT          1116
#define IDC_CHECK_SAVE                  1117
#define IDC_CHECK_COMPARE               1119
#define IDC_EDT_OP                      1119
#define IDC_BTN_CLEAR                   1120
#define IDC_CB_MARK                     1120
#define IDC_EDIT5                       1121
#define IDC_EDIT6                       1122
#define IDC_STATIC_COMPARE_TOTAL_COUNT  1123
#define IDC_EDIT_COMPARE_DATA           1124
#define IDC_RADIO_COMPARE_Z             1125
#define IDC_RADIO_COMPARE_RMS           1126
#define IDC_RADIO_COMPARE_X             1127
#define IDC_RADIO_COMPARE_Y             1128
#define IDC_STATIC_COMPARE_REVIEW       1129
#define IDC_STATIC_TYPE                 1130
#define IDC_STATIC_COMPARE_MARK         1131
#define IDC_STATIC_COMPARE_TOTAL        1132
#define IDC_CB_COMPARE_MARK             1135
#define IDC_PROGRESS1                   1136
#define IDC_PRG_REC                     1136
#define IDC_PROGRESS_WAIT               1136
#define IDC_STATIC_GROUP_GONOGO         1137
#define IDC_STATIC_TIME_UNIT            1138
#define IDC_STATIC_NOGONO_QUALIFI_UNIT  1140
#define IDC_STATIC_GONOGO_TEXT1         1141
#define IDC_STATIC_TEXT2                1142
#define IDC_EDIT_REPORT_WIDTH           1143
#define IDC_EDIT_REPORT_HEIGHT          1144
#define IDC_EDIT_COMPARE_FILENAME       1145
#define IDC_LSELPOS                     1146
#define IDC_STATIC_PROGRESSBAR_TEXT     1148
#define IDC_STATIC_TIMEVIEW             1149
#define ID_SETTINGS_COMPORTSETTING      32771
#define ID_SELECT_LOG_DIR               32772
#define ID_Open_Settings                32773
#define ID_Open_Set2tings               32774
#define ID_SAVE_SETTINGS                32775
#define ID_OPEN                         32776
#define ID_SAVE_SETTINGS_AS             32777
#define ID_SETTINGS_SHOWANNOTATIONDLALOG 32778
#define ID_Menu                         32779
#define ID_Menu32780                    32780
#define ID_OPTIONS                      32781
#define ID_SETTINGS_SETGO               32782
#define ID_SETTINGS_SETTRIGGERS         32783
#define ID_SETTINGS_SETSTATIONINFORMATION 32784
#define ID_SETTINGS_SETFILTER           32785
#define ID_SETTINGS_SETFFTSAMPLESIZE    32786
#define ID_SETTINGS_SETTIMEDOMAINFORMAT 32787
#define ID_SETTINGS_SELECTCOLORS        32788
#define ID_SETTRIGGERS                  32789
#define ID_SET_TRIGGERS                 32790
#define ID_SETTINGS_SETGONOGO           32791
#define ID_SETTINGS_ANNOTATION          32792
#define ID_SELECTCOLORS_RMS             32793
#define ID_SELECTCOLORS_X               32794
#define ID_SELECTCOLORS_Y               32795
#define ID_SELECTCOLORS_Z               32796
#define ID_SETTINGS_ENVIRONMENTSETTING  32797
#define ID_SETTINGS_MARKEDITOR          32798
#define ID_FILE_LOADCOMPAREDATA         32799
#define ID_EVENT_SETTINGS               32800
#define ID_SELECTCOLORS_TRIGGER         32801
#define ID_SELECTCOLORS_GO              32802
#define ID_SELECTCOLORS_SPECIN          32803
#define ID_SELECTCOLORS_SPECOUT         32804
#define ID_SELECTCOLORS_GONOGO          32805
#define ID_SELECTCOLORS_SPEC_IN         32806
#define ID_SELECTCOLORS_SPEC_OUT        32807
#define ID_FILE_OPENLOG                 32808
#define ID_VIEW_COMPAREDATA             32809
#define ID_VIEW_OVERLAY                 32810
#define ID_SELECTCOLORS_OVERLAY         32811
#define ID_SELECTCOLORS_MARKS           32812
#define ID_FILE_PARTIALSAVE             32813
#define ID_SELECTCOLORS_INDICATOR       32814
#define ID_FILE_SAVEAS                  32815
#define ID_FILE_LOADSETTINGSFROM        32816
#define ID_FILE_SAVECURRENTFILTEREDCSV  32817
#define ID_TEST_TESTFILEWRITE           32818
#define ID_                             32819

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        369
#define _APS_NEXT_COMMAND_VALUE         32820
#define _APS_NEXT_CONTROL_VALUE         1150
#define _APS_NEXT_SYMED_VALUE           346
#endif
#endif
