//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// APMDMonitor.rc에서 사용되고 있습니다.
//
#define IDOK                            1
#define IDP_OLE_INIT_FAILED             100
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_APMDMonitorTYPE             130
#define IDB_BITMAP1                     310
#define IDB_SESOMARK                    310
#define IDD_WARN_SET                    311
#define IDD_VIEW_OPTION                 312
#define IDD_STATUS                      314
#define IDD_MARKEDIT                    315
#define IDD_MODE                        316
#define IDD_GRAPH                       318
#define IDD_ENVSETTING                  319
#define IDD_COMSET                      320
#define IDI_ICON1                       322
#define IDD_STATUS_COMPARE              324
#define IDC_CBSCALEV                    1000
#define IDC_BUTTON1                     1000
#define IDC_BTN_SETFOLDER               1000
#define IDC_BTN_ITEMUP                  1000
#define IDC_STAT_LASER                  1001
#define IDC_CBSCALEHV                   1002
#define IDC_STAT_FAN                    1002
#define IDC_CBSCALEVU                   1003
#define IDC_STAT_BATTERY                1003
#define IDC_CBSCALEHVU                  1004
#define IDC_STAT_HUMI                   1004
#define IDC_RDISPMODE                   1005
#define IDC_SLD_POS                     1005
#define IDC_RDISPDEN                    1006
#define IDC_BTNMARKPREV                 1007
#define IDC_PLOT                        1007
#define IDC_BTNBMARKPREV                1007
#define IDC_BTNMARKADD                  1008
#define IDC_EDTPURGETIME                1008
#define IDC_BTNBMARKUPDATE              1008
#define IDC_BTNMARKDEL                  1009
#define IDC_BTNBMARKDEL                 1009
#define IDC_BTNMARKNEXT                 1010
#define IDC_SPGT                        1010
#define IDC_BTNBMARKNEXT                1010
#define IDC_EDTMARK                     1011
#define IDC_CBPT                        1011
#define IDC_RMODE                       1012
#define IDC_EDT_SAVEFOLDER              1012
#define IDC_RMODE2                      1013
#define IDC_EDT_DFNAME                  1013
#define IDC_BTNSS                       1014
#define IDC_EDTDGT                      1015
#define IDC_P01COUNT                    1015
#define IDC_SPIN1                       1016
#define IDC_SPPURGE                     1016
#define IDC_P03COUNT                    1016
#define IDC_CBDGTU                      1017
#define IDC_P05COUNT                    1017
#define IDC_PROGRESS1                   1018
#define IDC_PURGE_PROG                  1018
#define IDC_APMDTEMP                    1018
#define IDC_EDTTIMELABEL                1019
#define IDC_PRESSURE                    1019
#define IDC_CBPORTNO                    1020
#define IDC_CBBAUDRATE                  1021
#define IDC_CB_DISPPARTTYPE             1021
#define IDC_APMD_STATUS                 1022
#define IDC_TIME_TEXT                   1023
#define IDC_MEAS_PROG                   1024
#define IDC_EDT_MARKNAME                1025
#define IDC_LSTB_MARK                   1026
#define IDC_BTN_ITEMPDOWN               1027
#define IDC_BTN_ITEMDEL                 1028
#define IDC_BTN_ITEMINS                 1029
#define IDC_BTN_ITEMUPDATE              1030
#define IDC_BTN_ITEMLOAD                1032
#define IDC_BTN_ITEMSAVE                1034
#define IDC_BTN_ADD                     1035
#define IDC_CB_MARK                     1038
#define IDC_ADDMARK                     1039
#define IDC_EDT_MM                      1040
#define IDC_LST_STAT                    1041
#define IDC_EDTWARNTEMP                 1042
#define IDC_CHKUSETEMP                  1043
#define IDC_CHK_PAT01                   1044
#define IDC_USE_PAT03                   1045
#define IDC_USE_PAT05                   1046
#define IDC_EDTWARNP01                  1047
#define IDC_EDTWARNP03                  1048
#define IDC_EDTWARNP05                  1049
#define IDC_CB_SAMPLETIME               1050
#define IDC_CHK_WARN                    1051
#define IDC_EDT_WARN                    1054
#define IDC_EDT_POSTXT                  1056
#define IDC_HUMI_TEXT                   1058
#define IDC_STT_LABELP01                1059
#define IDC_STT_LABELP03                1060
#define IDC_STT_LABELP05                1061
#define IDC_STT_MAXPOS                  1063
#define IDC_BUTTON2                     1064
#define IDC_NXTMARK                     1066
#define IDC_EDT_POSMINTXT               1067
#define IDC_STT_MAXMINPOS               1068
#define IDC_LST_STATCMP                 1070
#define IDC_EDT_DIFF                    1071
#define IDC_COMPARE_PLOT                1072
#define ID_32771                        32771
#define ID_COMSET                       32772
#define ID_32773                        32773
#define ID_MARKEDITOR                   32774
#define ID_32775                        32775
#define ID_WARNSET                      32776
#define ID_32777                        32777
#define ID_ENVSET                       32778
#define ID_32779                        32779
#define ID_32780                        32780
#define ID_LOAD_COMPAREDATA             32781
#define ID_VIEW_COMPAREDATA             32782
#define IDM_OVERLAY                     32783
#define ID_OVERLAY                      32784

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1072
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
