#pragma once
#define SPACE_CAMX 5
#define SPACE_CAMY 5
#define CAM_HRES 2440
#define CAM_VRES 2048
#define WM_SCRN_UPDATE	WM_USER+1
#define WM_CAM_REMOTE	WM_USER+2
#define WM_SOCK_LISTEN	WM_USER+20
#define WM_SOCK_RECONNECT WM_USER+21
#define WM_SENDFN2REMOTE WM_USER+30
#define CFG_FILE _T("\\SCInspector.cfg")
#define PRODUCT_NAME _T("SCInspector10")
#define TIMEREVENT_GRAPCONTINUOUS	10
#define TIMEREVENT_DISPMOUSEPOSINFO 20
#define TIMEREVENT_DELOLDFILE		30
#define RESULT_FOLDER _T("Result")
#define BASE_SCREMOTEPORTNO 51000

//#define IGNORE_IO
