#pragma once
#define SPACE_CAMX 5
#define SPACE_CAMY 5
#define CAM_HRES 1280
#define CAM_VRES 1280
#define WM_SCRN_UPDATE	WM_USER+1
#define WM_CAM_REMOTE	WM_USER+2
#define WM_SOCK_LISTEN	WM_USER+20
#define WM_IMG_AS_TIME  WM_USER+40
#define WM_IMG_AS_TEMP  WM_USER+41
#define WM_AVI_RECSTART WM_USER+42
#define WM_AVI_RECSTOP  WM_USER+43
#define WM_AVI_AS_TIME  WM_USER+44
#define WM_AVI_AS_TEMP  WM_USER+45
#define WM_MAN_RECSTART	WM_USER+46
#define WM_MAN_RECSTOP  WM_USER+47
#define WM_XRAY_OFF		WM_USER+50
#define CFG_FILE _T("\\XNPI.cfg")
#define PRODUCT_NAME _T("XFMS10")
#define TIMEREVENT_GRAPCONTINUOUS	10
#define TIMEREVENT_DISPMOUSEPOSINFO 20
#define TIMEREVENT_DELOLDFILE		30
#define TIMEEVENT_READTEMP			40
#define TIME_LEGENDUPDATE			50
#define RESULT_FOLDER _T("Result")
#define BASE_SCREMOTEPORTNO 51000

//#define IGNORE_IO
